In [1]:
#import pandas
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

pip install pandas

pip install numpy

pip install skitlearn

pip install tiledbsoma --only-binary=:all:

pip install PyTDC

In [11]:
from tdc.multi_pred import DDI
data = DDI(name = 'DrugBank')

ModuleNotFoundError: No module named 'tdc'

In [2]:
#read the dataset
data = pd.read_csv(r'drug_interactions.csv')

In [3]:
# Using a method to control the rows and columns truncation
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 150)

In [4]:
#checking the dataset
data.head(10)

                Drug 1       Drug 2                            Interaction Description
0           Trioxsalen  Verteporfin  Trioxsalen may increase the photosensitizing a...
1  Aminolevulinic acid  Verteporfin  Aminolevulinic acid may increase the photosens...
2     Titanium dioxide  Verteporfin  Titanium dioxide may increase the photosensiti...
3     Tiaprofenic acid  Verteporfin  Tiaprofenic acid may increase the photosensiti...
4          Cyamemazine  Verteporfin  Cyamemazine may increase the photosensitizing ...
5           Temoporfin  Verteporfin  Temoporfin may increase the photosensitizing a...
6          Methoxsalen  Verteporfin  Methoxsalen may increase the photosensitizing ...
7   Hexaminolevulinate  Verteporfin  Hexaminolevulinate may increase the photosensi...
8         Benzophenone  Verteporfin  Benzophenone may increase the photosensitizing...
9           Riboflavin  Verteporfin  Riboflavin may increase the photosensitizing a...

In [5]:
#checking the columns of the dataset
list(data.columns)

['Drug 1', 'Drug 2', 'Interaction Description']

In [6]:
# Display the number of instances and features
data.shape

(191541, 3)

In [7]:
#checking the datatypes
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191541 entries, 0 to 191540
Data columns (total 3 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Drug 1                   191541 non-null  object
 1   Drug 2                   191541 non-null  object
 2   Interaction Description  191541 non-null  object
dtypes: object(3)
memory usage: 4.4+ MB

In [8]:
#describing data
data.describe()

               Drug 1       Drug 2                            Interaction Description
count          191541       191541                                             191541
unique           1634         1606                                             191541
top     Phenobarbital  Stiripentol  Trioxsalen may increase the photosensitizing a...
freq              858          736                                                  1

In [9]:
#checking null values
data.isnull().sum()

Drug 1                     0
Drug 2                     0
Interaction Description    0
dtype: int64

In [ ]:
#checking null value percentage
data.isna().sum()/len(data)*100

In [ ]:
null_columns = data.columns[data.isnull().any()]
print("Columns with null values:")
print(null_columns)

In [ ]:
# dropping null columns
data = data.drop(columns=(['HISPORX', 'RACEX', 'RACESECX', 'RACETERX', 'PRIMLANX', 'INHISPOX', 'INRACEX', 'INRASECX', 'INRATERX', 'INRELTOX', 'ARTHTYPX', 'ABUSX',
       'VB12DEF']))

In [ ]:
#checking unique values
data['NACCDAYS'].unique()

In [ ]:
# importing a Python package to visualise variables.
import plotly.express as px

In [ ]:
#checking anythings histogram
Grade_fig = px.histogram(data, x='NACCDAYS')
Grade_fig.show()

In [ ]:
# function to find outliers
def find_outliers_IQR(data):

  q1=data.quantile(0.25)

  q3=data.quantile(0.75)

  IQR=q3-q1

  outliers = data[((data < (q1 - 1.5 * IQR)) | (data > (q3 + 1.5 * IQR)))]

  return outliers

In [ ]:
# Finding outliers for anything
outliers = find_outliers_IQR(data['NACCDAYS'])

print("number of outliers: "+ str(len(outliers)))

outliers

In [ ]:
outlier_rows = data.index[data["NACCDAYS"] > 5000].tolist()
print(len(outlier_rows))
print(outlier_rows)

In [ ]:
# clipping values thtat are over 5000
data["NACCDAYS"] = data["NACCDAYS"].clip(upper=5000)

In [ ]:
# replacing string values with numerical values while making everything lowercase so no case sensitivity 
data['PACKET'] = data['PACKET'].map({'I': 1, 'F': 2, 'T': 3, 'IT': 4})

In [ ]:
#checking unique values 
data['EDUC'].unique()

In [ ]:

data['EDUC'] = data['EDUC'].replace(99, np.nan)
Mean_edu = data['EDUC'].mean()
data['EDUC'].fillna(Mean_edu, inplace=True)

In [ ]:
data.describe(include='float')

In [ ]:
data.describe(include='object')

In [ ]:
# Remove duplicate rows
data = data.drop_duplicates()

In [ ]:
# changing datatype float to int
data = data.astype({'FORMVER':"int", 'VISITMO':"int", 'VISITDAY':"int", 'VISITYR':"int", 'BIRTHMO':"int", 'BIRTHYR':"int", 'EDUC':"int", 'NACCDAYS':"int"})